### PR TITLE
Clear collections

### PR DESCRIPTION
**Pull request by spacedawwwg**
Clear collections (to prevent multiple additions of the same file)

### CODE REVIEW

**Comment by selvagsz** [comment]
Any update here ?

**Comment by PatrickHeneise** [comment]
@lambtron a merge would be highly appreciated.

**Comment by genexp** [comment]
Very nice.  Should commit

**Comment by rapodaca** [comment]
I'm using Metalsmith with collections and metalsmith-start with a blog. After saving a file, the articles cache is not cleared. This means that every post gets duplicated once for each reload.

This issue is addressed by applying the patch in the pull request.

Why not merge it?

**Comment by spacedawwwg** [comment]
Updated this to include 0.9.0 and updated the dev dependencies

**Comment by edhenderson** [comment]
@spacedawwwg Conflict I am afraid.

**Pull request merged**
